# Generated by Django 5.2.7 on 2025-11-06 01:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile_pics/default.png', upload_to=accounts.models.user_directory_path),
        ),
    ]
